export const GET_ALL_BREEDS_REQUEST = 'GET_ALL_BREEDS_REQUEST';
export const GET_ALL_BREEDS_SUCCESS = 'GET_ALL_BREEDS_SUCCESS';
export const GET_ALL_BREEDS_FAIL = 'GET_ALL_BREEDS_FAIL';

export const GET_BREED_INFO_REQUEST = 'GET_BREED_INFO_REQUEST';
export const GET_BREED_INFO_SUCCESS = 'GET_BREED_INFO_SUCCESS';
export const GET_BREED_INFO_FAIL = 'GET_BREED_INFO_FAIL';

export const GET_BREED_IMAGE_REQUEST = 'GET_BREED_IMAGE_REQUEST';
export const GET_BREED_IMAGE_SUCCESS = 'GET_BREED_IMAGE_SUCCESS';
export const GET_BREED_IMAGE_FAIL = 'GET_BREED_IMAGE_FAIL';

export const GET_SEARCH_BREEDS_REQUEST = 'GET_SEARCH_BREEDS_REQUEST';
export const GET_SEARCH_BREEDS_SUCCESS = 'GET_SEARCH_BREEDS_SUCCESS';
export const GET_SEARCH_BREEDS_FAIL = 'GET_SEARCH_BREEDS_FAIL';

export const UPDATE_SEARCH_BREEDS_TO_DB_REQUEST =
  'UPDATE_SEARCH_BREEDS_TO_DB_REQUEST';
export const UPDATE_SEARCH_BREEDS_TO_DB_SUCCESS =
  'UPDATE_SEARCH_BREEDS_TO_DB_SUCCESS';
export const UPDATE_SEARCH_BREEDS_TO_DB_FAIL =
  'UPDATE_SEARCH_BREEDS_TO_DB_FAIL';
